### ISSUE TITLE
Convert From Flow To Typescript

### ISSUE THREAD

**Issue by jasurkurbanov** [fullstackserverless/fullstackserverless.github.io#31]

**Comment by gHashTag** [comment]
I created a new repository at this [address](https://github.com/fullstackserverless/react-native-unicorn-uikit)

Please fix these errors:

1.In all cards, a problem with typing incoming objects
<img width="576" alt="Screenshot 2020-07-03 at 16 37 25" src="https://user-images.githubusercontent.com/6774813/86465757-b7ad3480-bd4b-11ea-84c5-a3204a332b66.png">

2. Not a mistake I know

<img width="655" alt="Screenshot 2020-07-03 at 16 43 58" src="https://user-images.githubusercontent.com/6774813/86466100-7a957200-bd4c-11ea-948b-0af4a26e5636.png">

3. Errors constants.ts

<img width="645" alt="Screenshot 2020-07-03 at 16 50 25" src="https://user-images.githubusercontent.com/6774813/86466602-5a19e780-bd4d-11ea-8839-39566d5ce49e.png">

<img width="612" alt="Screenshot 2020-07-03 at 16 51 01" src="https://user-images.githubusercontent.com/6774813/86466620-62722280-bd4d-11ea-8f88-bf10194e93d5.png">

4. Props in Header

<img width="411" alt="Screenshot 2020-07-03 at 17 50 28" src="https://user-images.githubusercontent.com/6774813/86470916-d284a680-bd55-11ea-8e4f-bcd1efdb4ccc.png">
